(function initContentModule(global) {
const lessons = {
  silabas: [
    "ma me mi mo mu", "pa pe pi po pu", "la le li lo lu", "sa se si so su",
    "ta te ti to tu", "na ne ni no nu", "ra re ri ro ru", "ca que qui co cu",
    "ba be bi bo bu", "da de di do du", "fa fe fi fo fu", "ga gue gui go gu",
  ],
  palabras_cortas: [
    "sol", "mar", "luz", "paz", "sal", "pez", "rio", "oro", "ola", "col",
    "oso", "ave", "pan", "uva", "ajo", "ojo", "pie", "dar", "ser", "ver",
    "son", "uno", "van", "fue", "hay", "ven", "ten", "pon", "si", "no",
    "ya", "mas", "mil", "mal", "tan", "muy", "sin", "por", "con", "dos",
    "rey", "mes", "ley", "fin", "voz", "don", "gol", "era", "vez", "ano",
    "gas", "tres", "bien", "tos", "sed", "res", "mio", "oda", "asi", "ir",
    "luna", "nube", "rosa", "lago", "flor", "nido", "maiz", "duna", "lava", "rana",
    "lodo", "polo", "lena", "loma", "toro", "puma", "pato", "loro", "gato", "mula",
    "buey", "cria", "taco", "sopa", "miel", "coco", "papa", "lima", "higo", "yuca",
    "nabo", "mote", "nino", "nina", "mama", "papa", "bebe", "mano", "boca", "dedo",
    "pelo", "cara", "mesa", "casa", "ropa", "sala", "tela", "mapa", "vela", "bola",
    "bota", "fila", "hoja", "hola", "isla", "joya", "jugo", "kilo", "loco", "lupa",
    "tema", "tubo", "rojo", "azul", "gris", "lila", "alto", "bajo", "rico", "sano",
    "liso", "duro", "fino", "puro", "tipo", "tope", "tuna", "cola", "nuca", "leer",
    "amar", "amor", "beso", "vida", "vino", "vaca", "vale", "vena", "tren", "oido",
    "alma", "foca", "lona", "lomo", "toma", "visa",
  ],
  palabras_medianas: [
    "arbol", "lluvia", "camino", "jardin", "pelota", "musica", "amigos",
    "viento", "tierra", "verano", "puerta", "espejo", "tiempo", "trabajo",
    "bosque", "ciudad", "flores", "regalo", "escuela", "tambor", "cohete",
    "playa", "brillo", "cielo", "noche", "tarde", "campo", "cerro", "arroyo",
    "piedra", "monte", "bahia", "sierra", "palmar", "laguna", "selva",
    "perro", "pajaro", "raton", "caballo", "conejo", "tortuga", "iguana",
    "lagarto", "burro", "ardilla", "mapache", "coyote", "venado", "jabali",
    "grillo", "abeja", "mosca", "delfin", "alacran", "zorrillo",
    "tacos", "tamales", "pozole", "menudo", "birria", "elotes", "gordita",
    "tostada", "atole", "elote", "chile", "mango", "guayaba", "pepino",
    "jicama", "tlayuda", "tepache", "camote", "zapote", "platano", "naranja",
    "limon", "chayote", "carnita", "machaca", "memela", "chalupa", "tamal",
    "abuelo", "abuela", "hermano", "hermana", "primo", "vecino", "familia",
    "lapiz", "papel", "tijeras", "pintura", "maestra", "alumno", "recreo",
    "salon", "mochila", "examen", "crayon", "pincel", "tarea", "clase", "libro",
    "cabeza", "brazo", "pierna", "rodilla", "hombro", "espalda", "barriga",
    "mejilla", "oreja", "cuarto", "ventana", "pared", "suelo", "techo", "pasillo",
    "garage", "cocina", "colima", "volcan", "comala", "palmera", "danzon",
    "tecoman", "armeria", "puerto", "muelle", "malecon", "costera",
    "celular", "tablet", "bocina", "cable", "senal", "mensaje", "llamada",
    "verde", "negro", "blanco", "morado", "rosado", "dorado", "colores",
    "bonita", "alegre", "fuerte", "tierno", "suave", "grande", "gordo", "flaco",
    "moreno", "chico", "lindo", "bueno", "triste", "feliz", "rapido", "lento",
    "limpio", "sucio", "nuevo", "viejo", "bonito", "facil", "dificil",
    "bombero", "doctor", "musico", "pintor", "torero", "maices", "mangos",
    "cocos", "limones", "nopales",
  ],
  palabras_largas: [
    "mariposa", "elefante", "serpiente", "cocodrilo", "guajolote", "chapulin",
    "tlacuache", "tecolote", "escorpion", "cangrejo", "guacamole", "aguacate",
    "tamarindo", "enchilada", "guanabana", "carnitas", "gorditas", "tostadas",
    "chayotes", "palmeras", "coquitos", "naranjas", "mazapanes", "quesillo",
    "computadora", "calculadora", "reproductor", "television", "ventilador",
    "pantalla", "cargador", "cuaderno", "borrador", "pizarron", "presidente",
    "gobernador", "secretaria", "periodista", "arquitecto", "veterinario",
    "electricista", "carpintero", "enfermera", "dentista", "electricidad",
    "telescopio", "temperatura", "fotografia", "equilibrio", "madrugada",
    "manzanillo", "dinosaurio", "universidad", "biblioteca", "laboratorio",
    "supermercado", "restaurante", "aeropuerto", "estacionamiento",
    "departamento", "bicicleta", "automovil", "cumpleanos", "refrigerador",
    "helicoptero", "submarino", "diccionario", "calendario", "matematicas",
    "paraguas", "administracion", "investigacion", "conversacion",
    "participacion", "pronunciacion", "comprension", "independencia",
    "constitucion", "revolucion", "celebracion", "decoracion", "comunicacion",
    "construccion", "responsabilidad", "entretenimiento", "funcionamiento",
    "contabilidad",
  ],
  frases_cortas: [
    "El sol brilla hoy", "La luna es bella", "El cielo esta azul",
    "El agua esta fria", "La lluvia cayo fuerte", "El viento sopla fuerte",
    "El rio esta lleno", "El maiz es rico", "El volcan humea hoy",
    "La flor huele bien", "La noche esta fria", "El lago es grande",
    "El perro corre rapido", "Mi gato es cafe", "El pato nada bien",
    "La rosa es roja", "El toro es grande", "El oso es cafe",
    "La abeja pica mucho", "El loro habla claro", "El burro camina lento",
    "Mama hace pan rico", "El nino come manzana", "Mi mama me quiere",
    "Papa trabaja mucho", "Mi hermano es alto", "Tengo seis anos",
    "Mi abuela hace tamales", "La maestra es buena", "Mi casa es grande",
    "Me gusta el chocolate", "Me gustan los tacos", "El mango esta dulce",
    "La naranja es rica", "El pan esta caliente", "Quiero agua fria",
    "La palma da cocos", "Tengo un libro rojo", "Voy a la escuela",
    "Juego con mis amigos", "La mariposa vuela alto", "Tengo tarea hoy",
    "El recreo ya llego", "Me gustan las frutas", "Soy buen alumno",
    "Voy al parque", "Me duele la cabeza", "Me lavo las manos",
    "Me duele el pie", "Tengo hambre ahora", "Tengo sed y hambre",
    "Me duele la panza", "Colima es bonita", "Hoy no hay clases",
    "La luna brilla mucho", "El sol es grande", "Mi perro se llama Rex",
    "Los peces nadan juntos", "El arbol tiene hojas", "El cielo tiene nubes",
    "Quiero jugar futbol",
  ],
  frases_medianas: [
    "El perro juega en el jardin verde", "Las mariposas vuelan sobre las flores",
    "El caballo corre libre por el potrero", "Vi una iguana grande en el arroyo",
    "El rio corre entre las montanas altas", "Los pajaros cantan bonito en la manana",
    "La lluvia cae sobre los arboles grandes", "El sol calienta toda la ciudad hoy",
    "La ardilla salta de arbol en arbol", "El cocodrilo vive cerca del rio tranquilo",
    "El delfin nada muy rapido en el mar", "El coyote aulla en la noche oscura",
    "El tlacuache se esconde entre los arboles", "Las tortugas nadan lento en el lago",
    "El grillo canta toda la noche fuerte", "Encontramos un conejo chiquito en el jardin",
    "Me gustan los tacos de pollo con salsa", "Mama prepara la cena con mucho amor",
    "Mi abuela hace pozole rojo los jueves", "Hoy hay birria de res en mi casa",
    "Los chapulines se comen con sal y limon", "Los chayotes del mercado estan muy frescos",
    "Voy al mercado con mi abuelita querida", "Mi abuela sabe hacer guacamole muy rico",
    "En Tecoman hay muchos limones y cocos", "Los cocos caen de las palmeras altas",
    "La maestra ensena en la escuela cada dia", "Saque diez en el examen de matematicas",
    "Mi mochila tiene libros y cuadernos nuevos", "El recreo dura veinte minutos cada dia",
    "Hoy aprendimos las tablas de multiplicar", "Mi companero me presto un lapiz rojo",
    "La directora hablo con todos los alumnos", "Manana hay excursion al museo de la ciudad",
    "El maestro escribe en el pizarron verde", "El libro tiene muchas paginas con dibujos",
    "Mi hermana aprende a tocar la flauta dulce", "Los alumnos leen en voz alta en clase",
    "Mi papa trabaja en una tienda del centro", "Mi mama me lleva a la escuela cada manana",
    "Mi abuelo me cuenta cuentos por las noches", "Mi hermana y yo jugamos en el patio juntos",
    "Los domingos vamos a comer con la familia", "Mi tia vive en una casa cerca del rio",
    "El perro de mi vecino ladra muy fuerte", "Mi primo juega futbol en el parque verde",
    "Voy con mi mama al mercado los sabados", "La pelota rueda por todo el patio escolar",
    "El volcan de Colima se ve muy bonito", "Las palmeras crecen en toda la costa verde",
    "El danzon se baila en el jardin principal", "El calor de Colima es muy fuerte hoy",
    "Vamos a la playa de Manzanillo en verano", "Los limones de Tecoman son los mejores",
    "La costera de Manzanillo es muy bonita", "Los flamboyanes florecen en la ciudad capital",
    "Debo lavarme los dientes antes de dormir", "Es importante comer frutas y verduras frescas",
    "Mi perro come su comida todas las mananas", "El maestro llego muy temprano a la escuela",
  ],
  frases_largas: [
    "El nino corre feliz por el parque verde de la ciudad",
    "La mariposa vuela sobre las flores del jardin de mi abuela",
    "El arbol grande de mi jardin tiene muchas ramas llenas de hojas",
    "La luna brilla muy bonito en el cielo oscuro y estrellado",
    "Los flamboyanes florecen de color rojo en las calles de la ciudad",
    "El rio Armeria pasa por varios municipios del estado de Colima",
    "Durante la temporada de lluvias los cerros de Colima se ponen verdes",
    "Los chapulines son insectos que se comen tostados con sal y chile",
    "El tlacuache se pasea de noche buscando fruta y agua fresca",
    "El cocodrilo puede nadar muy rapido y tambien correr en tierra",
    "Los coyotes aullan en la noche oscura cuando hay luna llena",
    "Los venados corren muy rapido cuando sienten peligro en el bosque",
    "El volcan de Colima se puede ver desde muchos pueblos del estado",
    "Las fiestas de Colima tienen musica de mariachi y danzon en el jardin",
    "Mi familia viaja a Manzanillo para ver el mar y comer mariscos frescos",
    "Los limones de Tecoman son los mas famosos de todo Mexico y el mundo",
    "En la feria de Colima hay juegos mecanicos comida y musica toda la noche",
    "Mi abuela me enseno a hacer tamales de rajas con queso y chile verde",
    "El mercado Constitucion tiene frutas verduras y artesanias de todo Colima",
    "Los cocos de Manzanillo son muy ricos con limon y chile en polvo",
    "Mi mama hace atole de guayaba caliente cuando hace mucho frio",
    "Los charros de Colima son muy valientes y habilidosos con el lazo",
    "Todos los dias voy a la escuela caminando con mis amigos del barrio",
    "La maestra nos explico como se forman las nubes en el cielo azul",
    "Aprender a leer es muy importante para poder estudiar toda la vida",
    "En la biblioteca de la escuela hay muchos libros de cuentos y ciencias",
    "Mi companero y yo hicimos una maqueta del sistema solar con carton",
    "La directora premiara a los alumnos que lean mas libros este ano",
    "El maestro nos pidio que leyeramos un libro completo por semana",
    "En la noche escucho a los grillos cantar cerca de mi ventana",
    "Mi familia y yo comemos juntos en la mesa todos los domingos",
    "Mi abuelita hace tamales deliciosos cada ano para las posadas de diciembre",
    "El chocolate caliente sabe muy rico en las mananas de frio intenso",
    "Los ninos juegan futbol en el parque cuando termina la escuela por la tarde",
    "Mi abuelo me cuenta historias de cuando el era nino pequeno en el rancho",
    "Es importante ayudar a nuestros companeros cuando tienen alguna dificultad",
    "Mi mama me enseno a decir gracias por favor y buenos dias siempre",
    "Cuidar el medio ambiente es responsabilidad de todos los ninos y adultos",
    "Los amigos verdaderos se ayudan y se respetan en todo momento del dia",
    "Mi familia festeja el dia de muertos con ofrendas de flores y comida",
  ],
};

const extraLessons = {
  silabas: [
    "ha he hi ho hu", "ka ke ki ko ku", "wa we wi wo wu", "xa xe xi xo xu",
    "cha che chi cho chu", "lla lle lli llo llu", "rra rre rri rro rru",
    "bra bre bri bro bru", "bla ble bli blo blu", "pra pre pri pro pru",
    "pla ple pli plo plu", "tra tre tri tro tru", "cla cle cli clo clu",
    "cra cre cri cro cru", "gra gre gri gro gru", "dra dre dri dro dru",
    "fra fre fri fro fru", "fla fle fli flo flu",
  ],
  palabras_cortas: [
    "el", "la", "los", "las", "un", "una", "unos", "unas", "y", "o",
    "de", "del", "al", "en", "con", "por", "mi", "tu", "su", "soy",
    "yo", "se", "me", "te", "le", "lo", "nos", "va", "veo", "come",
    "mira", "salta", "rie", "libro", "agua", "dia", "mano", "ojo", "pie", "feliz",
    "cal", "can", "dan", "fan", "bar", "par", "pal", "mal", "mas", "mis",
    "tus", "sus", "ves", "vas", "voy", "fui", "ira", "uso", "ama", "aro",
    "eco", "ese", "isa", "oca", "oca", "oca", "cuna", "cama", "copa", "cima",
    "piso", "peso", "pesa", "paso", "pase", "mina", "mono", "mimo", "misa", "masa",
    "nana", "nene", "nona", "nena", "nudo", "sana", "seno", "suma", "sapo", "seda",
    "taza", "tiza", "tela", "tono", "tapa", "dado", "dama", "dona", "duda", "dije",
    "faro", "fino", "fama", "fumo", "feta", "goma", "gula", "gana", "gira", "giro",
    "jugo", "jefa", "jota", "jura", "vivo", "vela", "voto", "vaso", "zumo", "zona",
  ],
  palabras_medianas: [
    "porque", "cuando", "como", "pero", "aunque", "mientras", "entonces", "despues",
    "antes", "tambien", "siempre", "nunca", "ahora", "todavia", "tanto", "todo",
    "cada", "otro", "otra", "poco", "casi", "entre", "sobre", "hacia",
    "desde", "hasta", "tener", "hacer", "poder", "querer", "saber", "decir",
    "poner", "venir", "salir", "llevar", "traer", "tengo", "tiene", "puedo",
    "vamos", "tienen", "habia", "tenia", "eran", "fueron", "estaba", "estan",
    "amiga", "cuento", "palabra", "numero", "veces", "dentro", "afuera", "arriba",
    "abajo", "cerca", "lejos", "pronto", "luego", "junto", "igual", "mejor",
    "dulce", "salado", "caliente", "helado", "mojado", "seco", "redondo", "cuadrado",
    "plato", "vasito", "cuchara", "tenedor", "zapato", "camisa", "sueter", "sombrero",
    "cepillo", "jaboncito", "toalla", "patio", "cancha", "banca", "paredes", "puertas",
    "familias", "maestros", "lectura", "dictado", "sonido", "silaba", "vocales", "letras",
    "cuento", "pagina", "renglon", "titulo", "dibujo", "tarjeta", "premio", "avance",
  ],
  palabras_largas: [
    "aprendizaje", "abecedario", "consonantes", "vocalizacion", "entonacion", "diccion",
    "ortografia", "vocabulario", "imaginacion", "curiosidad", "observacion", "explicacion",
    "instruccion", "educacion", "naturaleza", "experimento", "maravilloso", "silencioso",
    "cuidadoso", "respetuoso", "organizado", "compartido", "divertido", "colorido",
    "bibliotecario", "cuentacuentos", "companerismo", "responsable", "participante", "estudiante",
    "profesora", "directora", "secretario", "enfermeria", "deportista", "campesino",
    "panadero", "pescador", "jardinero", "mecanico", "fotografo", "cientifico",
    "rinoceronte", "hipopotamo", "jirafita", "golondrina", "colibri", "pelicano",
    "zanahoria", "calabacita", "jitomate", "mandarina", "sandia", "lechuga",
    "desayuno", "almuerzo", "merienda", "cazuela", "molcajete", "licuadora",
    "computacion", "microfono", "audifonos", "bibliografia", "geografia", "historia",
  ],
  frases_cortas: [
    "Yo veo una casa", "Mi mama lee", "Papa toma agua", "La mesa es roja",
    "El nino mira", "La nina salta", "Tengo un libro", "Veo una flor",
    "El perro ladra", "Mi gato duerme", "La sopa esta caliente", "El pan es dulce",
    "Vamos a leer", "Quiero jugar hoy", "Tengo mucha sed", "Mira mi dibujo",
    "La clase empieza", "El cuento termina", "Mi mano limpia", "El sol calienta",
    "La luna sale", "El agua corre", "La pelota bota", "El lapiz pinta",
    "La maestra habla", "El alumno escucha", "Todos leen juntos", "Mi amigo viene",
    "La puerta abre", "La ventana cierra", "El patio suena", "La mochila pesa",
  ],
  frases_medianas: [
    "El nino lee una palabra nueva", "La nina escribe su nombre completo",
    "Mi amigo cuenta hasta veinte despacio", "La maestra revisa la tarea del grupo",
    "El libro tiene dibujos grandes y claros", "Todos escuchan el cuento con atencion",
    "Mi mama me ayuda a leer cada tarde", "Papa prepara agua fresca para todos",
    "El alumno practica silabas antes de jugar", "La clase empieza cuando todos llegan",
    "Hoy leimos palabras cortas en voz alta", "La pelota roja rueda por la cancha",
    "Mi mochila tiene cuadernos lapices y colores", "El patio de la escuela esta limpio",
    "La familia come junta en la mesa", "Despues de leer salimos al recreo",
    "Cada palabra nueva me ayuda mucho", "Puedo leer mejor si practico diario",
    "El maestro guarda los registros del juego", "La nina avanza cuando lee con calma",
    "El microfono escucha la voz del alumno", "Las consonantes aparecen poco a poco",
    "Mi grupo practica lectura todos los dias", "El cuento corto habla de una casa",
  ],
  frases_largas: [
    "El alumno lee una frase completa mientras la maestra observa su avance",
    "Cuando practicamos todos los dias las palabras nuevas se vuelven mas faciles",
    "La nina mira el dibujo del cuento y despues lee la oracion con calma",
    "Mi maestro preparo una partida especial con consonantes que ya conocemos",
    "En la escuela aprendemos a escuchar pensar leer y compartir nuestras ideas",
    "Cada estudiante tiene su propio ritmo y puede mejorar con practica constante",
    "El juego muestra una palabra nueva y el alumno la lee en voz alta",
    "Despues de terminar la lectura el registro queda guardado para revisarlo",
    "La familia puede ayudar en casa leyendo cuentos cortos durante la tarde",
    "Cuando una palabra parece dificil respiramos despacio y volvemos a intentarlo",
    "La maestra elige el nivel inicial y la meta de ejercicios para cada alumno",
    "Las consonantes seleccionadas ayudan a preparar lecturas adecuadas para el grupo",
    "El alumno escucha la indicacion mira la pantalla y comienza a leer tranquilo",
    "Con cada partida completada el estudiante gana confianza para leer textos nuevos",
  ],
};

Object.entries(extraLessons).forEach(([level, items]) => {
  lessons[level] = [...new Set([...(lessons[level] || []), ...items])];
});

const defaultConsonants = [
  "m", "p", "l", "s", "t", "n", "r", "c", "q", "b", "d", "f", "g", "j", "v", "z", "y", "h", "k", "w", "x", "ch", "ll", "rr",
];
const defaultGameConfig = {
  consonants: [...defaultConsonants],
  levelStart: "silabas",
  sessionGoal: 10,
  shuffleSyllables: false,
  maxAttemptsPerChunk: 3,
  notes: "",
};

function getLessons() {
  return lessons;
}

function getDefaultGameConfig() {
  return { ...defaultGameConfig, consonants: [...defaultGameConfig.consonants] };
}

global.LectoVozContent = {
  lessons,
  extraLessons,
  defaultConsonants,
  defaultGameConfig,
  getLessons,
  getDefaultGameConfig,
};
})(typeof window !== "undefined" ? window : globalThis);
